version: '3'
services:
  validator:
    image: developmentseed/cvat_validator:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CVAT_API: http//192.168.1.39:8080
    ports:
      - '3000:80'